"""15.11.24 fisrt commit

Revision ID: 5140473c1c37
Revises: 
Create Date: 2024-11-15 11:58:45.776477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5140473c1c37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('goods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('полное наименование товара', sa.String(length=128), nullable=True),
    sa.Column('введите артикул товара с сайта wildberries', sa.Integer(), nullable=True),
    sa.Column('fk_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=True),
    sa.Column('выберите товар для отслеживания', sa.Integer(), nullable=True),
    sa.Column('выберите интервал отслеживания', sa.Enum('HOUR', 'TWELVE_H', 'TWENTY_FOUR_H', 'TEST', name='time_choice'), nullable=True),
    sa.Column('дата начала отслеживания', sa.DateTime(), nullable=True),
    sa.Column('введите дату окончания отслеживания', sa.DateTime(), nullable=True),
    sa.Column('Задача запущена', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['выберите товар для отслеживания'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tracked_goods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=True),
    sa.Column('fk_goods', sa.Integer(), nullable=True),
    sa.Column('брэнд', sa.String(length=32), nullable=True),
    sa.Column('цена товара', sa.Float(), nullable=True),
    sa.Column('дата время', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_goods'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tracked_goods')
    op.drop_table('tasks')
    op.drop_table('goods')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
